### ISSUE TITLE
Too long and too short

### ISSUE THREAD

**Issue by GaelGil** [GaelGil/notebooks#2]
In my book genre predicting notebook what would be a good way to remove really long and really short words. What is too short and too long. Should I research this or try it out different lengths.

**Comment by camoverride** [comment]
There are multiple ways to think about this problem -- I'm not going to give you an exact answer because one doesn't exist:

1) Best practices: do general guidelines for dealing with this exist? If they do, they can probably be found by Googling. Are the general guidelines worth applying? Do they apply to this specific scenario? Can you trust the guidelines? Do you need to understand their purpose? For instance, it's generally suggested that you remove all [stopwords](https://en.wikipedia.org/wiki/Stop_words) before you start modeling, as they generally don't influence model performance.

2) DIY: think about what _removing long words_ actually means and do the research for yourself. If the point of removing long words is to get rid of text errors (like _thissentencethat'smissingspacesforsomereason_), then there are multiple ways of dealing with it: A) remove every word that [only occurs once](https://en.wikipedia.org/wiki/Hapax_legomenon), B) remove the least frequent N% of words, or maybe C) remove words longer than _k_ letters if those words aren't in the dictionary. In turn, _B_ might be part of a general principle/guideline, or you might be able to figure it out with the next point:

3) Include _max word length_ as a hyper-parameter when modeling. For instance, build two models, A and B, where both models have different thresholds for _long words_. See which model has better performance.

**Comment by GaelGil** [comment]
this notebook does not exist anymore
